In [2]:
import pandas as pd
import altair as alt

alt.data_transformers.enable('vegafusion')

DataTransformerRegistry.enable('vegafusion')

In [3]:
items = pd.read_csv('items.csv')
sales = pd.read_csv('sales.csv')
merged = pd.merge(sales,items,on = "item_name")

print(sales["time"].max())
print(sales["time"].min())

15:59:59
07:00:02

In [4]:
sales["time"] = pd.to_datetime(sales["time"])

time_split = pd.to_datetime("11:30:00").time()

morningPerson = sales[sales["time"].dt.time < time_split].reset_index()

morningPerson

C:\Users\Tsjng\AppData\Local\Temp\ipykernel_4952\947469687.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  sales["time"] = pd.to_datetime(sales["time"])

,index,date,time,item_name,transaction_type,own_cup,surcharge,customer_id
0,0,2022-01-01,2025-11-22 07:03:30,Cold Brew,Takeout,True,False,26946
1,1,2022-01-01,2025-11-22 07:30:58,Iced Coffee,Takeout,True,False,24356
2,2,2022-01-01,2025-11-22 08:32:23,Iced Latte,Takeout,False,False,3760
3,3,2022-01-01,2025-11-22 08:45:03,Latte,Dine-in,True,False,5900
4,4,2022-01-01,2025-11-22 09:03:47,Latte,Takeout,False,False,11589
...,...,...,...,...,...,...,...,...
17523,32588,2024-12-31,2025-11-22 10:01:42,Americano,Takeout,False,True,24356
17524,32589,2024-12-31,2025-11-22 10:44:21,Mocha,Dine-in,False,False,28719
17525,32590,2024-12-31,2025-11-22 10:50:03,Matcha Latte,Takeout,False,True,517
17526,32591,2024-12-31,2025-11-22 11:15:27,Cold Brew,Dine-in,False,False,15989
17527,32592,2024-12-31,2025-11-22 11:20:46,Mocha,Dine-in,True,False,2797

In [5]:
afternoonPerson = sales[sales["time"].dt.time >= time_split].reset_index()

afternoonPerson

,index,date,time,item_name,transaction_type,own_cup,surcharge,customer_id
0,11,2022-01-01,2025-11-22 11:37:42,Matcha Latte,Takeout,False,False,22643
1,12,2022-01-01,2025-11-22 11:51:50,Cold Brew,Takeout,True,False,20890
2,13,2022-01-01,2025-11-22 12:35:16,Iced Latte,Takeout,True,False,24017
3,14,2022-01-01,2025-11-22 14:04:54,Latte,Takeout,True,False,25267
4,15,2022-01-01,2025-11-22 15:30:23,Cold Brew,Dine-in,True,False,7962
...,...,...,...,...,...,...,...,...
15072,32600,2024-12-31,2025-11-22 14:07:18,Green Tea,Dine-in,False,False,21936
15073,32601,2024-12-31,2025-11-22 14:24:08,Latte,Takeout,True,False,15914
15074,32602,2024-12-31,2025-11-22 14:36:31,Chai Latte,Dine-in,True,False,15227
15075,32603,2024-12-31,2025-11-22 14:57:19,Cappuccino,Takeout,True,False,21314
15076,32604,2024-12-31,2025-11-22 15:30:12,Espresso,Dine-in,False,False,11063

In [6]:
morningPerson["date"] = pd.to_datetime(morningPerson["date"])

morningPerson["year_month"] = morningPerson["date"].dt.strftime('%B %Y')

morning_monthly = morningPerson.drop(columns=["index", "date", "time", "transaction_type", "own_cup", "surcharge", "customer_id"])

morning_monthly = morning_monthly.groupby(['item_name', 'year_month']).size().reset_index(name='purchases')

morning_monthly['year_month'] = pd.to_datetime(morning_monthly['year_month'], format='%B %Y')

morning_monthly = morning_monthly.sort_values(by='year_month')

morning_monthly_graph = alt.Chart(morning_monthly).mark_line().encode(
    x = alt.X("year_month").title("Month"),
    y = alt.Y("purchases").title("Number of Purchases"),
    color = alt.Color("item_name").title("Item")
).facet(
    facet = alt.Facet("item_name").title("Number of Items Purchased over Time for Morning People"),
    columns = 3
)

morning_monthly_graph

alt.FacetChart(...)

In [8]:
afternoonPerson["date"] = pd.to_datetime(afternoonPerson["date"])

afternoonPerson["year_month"] = afternoonPerson["date"].dt.strftime('%B %Y')

afternoon_monthly = afternoonPerson.drop(columns=["index", "date", "time", "transaction_type", "own_cup", "surcharge", "customer_id"])

afternoon_monthly = afternoon_monthly.groupby(['item_name', 'year_month']).size().reset_index(name='purchases')

afternoon_monthly['year_month'] = pd.to_datetime(afternoon_monthly['year_month'], format='%B %Y')

afternoon_monthly = afternoon_monthly.sort_values(by='year_month')

afternoon_monthly_graph = alt.Chart(afternoon_monthly).mark_area().encode(
    x = alt.X("year_month").title("Month"),
    y = alt.Y("purchases").title("Number of Purchases"),
    color = alt.Color("item_name").title("Item")
)

afternoon_monthly_graph

alt.Chart(...)